# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/131N2_dO0akHlSYsmljHVwzJZpSPQYexp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#1
data  = pd.read_csv("/content/drive/MyDrive/Walmart_Dataset Python_Final_Assessment.csv")
df = pd.DataFrame(data)

dataset_info  = df.info()
print(dataset_info)

column_analysis = df.head()
print(column_analysis)

null_count = df.isnull().sum()
print(null_count)

#2
data  = pd.read_csv("/content/drive/MyDrive/Walmart_Dataset Python_Final_Assessment.csv")
df = pd.DataFrame(data)

check_null = df.isnull().sum()
print(check_null)
#there is no null values in the dataset

#In case of null values removing the null values
df.dropna()

check_duplicate  = df[df.duplicated()]
print("check_duplicate")

#removing duplicates
df.drop_duplicates()

#3
data  = pd.read_csv("/content/drive/MyDrive/Walmart_Dataset Python_Final_Assessment.csv")
df = pd.DataFrame(data)
measures = df.describe()
print(measures)

#4
#profit
data  = pd.read_csv("/content/drive/MyDrive/Walmart_Dataset Python_Final_Assessment.csv")
df = pd.DataFrame(data)

categorywise_sales = df.groupby("Category").agg(
    profit = ("Profit" ,"sum")).reset_index()
print(categorywise_sales)
plt.figure(figsize=(19,5))
plt.bar(categorywise_sales["Category"],categorywise_sales["profit"])

plt.title("categorywise profit")

plt.show()

print("copiers, Blinders, Accessories are the top 3 category in terms of profit")
print("Bookcase, Machines are the poorly performing categories in terms of profit")


#sales
categorywise_sales = df.groupby(["Category"]).agg(
    sales = ("Sales" ,"sum")).reset_index()
print(categorywise_sales)
plt.figure(figsize=(19,5))
plt.bar(categorywise_sales["Category"],categorywise_sales["sales"])
plt.title("categorywise profit")

plt.show()
print("")

#5
data  = pd.read_csv("/content/drive/MyDrive/Walmart_Dataset Python_Final_Assessment.csv")
df = pd.DataFrame(data)
corelation  = df.corr()
sns.heatmap(data=corelation)
plt.title("corelation between variables")
plt.show()

#6
data  = pd.read_csv("/content/drive/MyDrive/Walmart_Dataset Python_Final_Assessment.csv")
df = pd.DataFrame(data)
sns.boxplot(df)
plt.title("finding outliers",color="green")
plt.show()

print("on checking for outliers there are outliers in sales and profit")

#7 #1
import datetime as dt
data  = pd.read_csv("/content/drive/MyDrive/Walmart_Dataset Python_Final_Assessment.csv")
df = pd.DataFrame(data)

df1  = df.groupby("Order Date").agg(
    sales= ("Sales" , "sum"),
    profit = ("Profit","sum")
)
df1

df1.plot(kind='line', figsize=(8, 4), title='sales')
plt.gca().spines[['top', 'right']].set_visible(True)

print("It is clear that profit and sales drops after newyear as people have purchased more for christmas and newyear")

print("After every festival seson there is a drop in sales and profit")

#7
#2

data  = pd.read_csv("/content/drive/MyDrive/Walmart_Dataset Python_Final_Assessment.csv")
df = pd.DataFrame(data)

categorywise_sales = df.groupby(["Category"]).agg(
    sales = ("Sales" ,"sum")).reset_index()
print(categorywise_sales)
plt.figure(figsize=(19,5))
plt.bar(categorywise_sales["Category"],categorywise_sales["sales"])

plt.title("categorywise profit")

plt.show()
print("Chairs and phones have shown growth ")

#7
#3

data  = pd.read_csv("/content/drive/MyDrive/Walmart_Dataset Python_Final_Assessment.csv")
df = pd.DataFrame(data)

customer  = df.groupby("EmailID").agg(
    nooforders  = ("Order ID","count"),
    sales  = ("Sales","sum")

)
print(customer)

topcustomerbyorders  =  customer["nooforders"].max()
topcustomerbysales =  customer["sales"].max()

topcustomerbyorders
topcustomerbysales

#7
#4
data  = pd.read_csv("/content/drive/MyDrive/Walmart_Dataset Python_Final_Assessment.csv")
df = pd.DataFrame(data)

customer  = df.groupby("EmailID").agg(
    averagetime  =  ("Order Date","mean")
)
customer
print("customer with less average purchase time buy more frequently")

#7
#5
import datetime as dt
data  = pd.read_csv("/content/drive/MyDrive/Walmart_Dataset Python_Final_Assessment.csv")
df = pd.DataFrame(data)
df["Order Date"] = df["Order Date"].astype(date)
df["Order Date"] =df["Order Date"].astype(date)
df["deliveryTime"] = df["Order Date"] - df["Ship Date"]

print("on understanding the data set  the supply chain optimization can be done by improving and motivating the local seller")
print("delivery time inceases as the order has to travel from diffrent region to region")

#7
#6

data  = pd.read_csv("/content/drive/MyDrive/Walmart_Dataset Python_Final_Assessment.csv")
df = pd.DataFrame(data)

categorywise_sales = df.groupby("Geography").agg(
    profit = ("Sales" ,"sum")).reset_index()


filter  =  categorywise_sales[categorywise_sales["profit"]>10000]["Geography"]
print("Geography with top 5 sales amount ")
print(filter)

print()
print()
filterl  =  categorywise_sales[categorywise_sales["profit"]<1000]["Geography"]
print("Geography with bottom 5 sales amount ")
print(filterl)


print("it is clear that regions where technology,buisness grows is the region where sales is high ")
print("In region of buisness growth people need more products")
print("Where in non buisness area product sales is less ")

plt.figure(figsize=(20,5))
plt.bar(categorywise_sales["Geography"],categorywise_sales["profit"])

plt.title("categorywise profit")

print(categorywise_sales)
plt.show()

#7
#7

print("on analysing the dataset wer can conclude that high value customers are buisness owners where they purchase fot large amount for their buisnessess")
print("To improve customer loyalty discounts are vital and as they are high value customers delivery time should be reduced user experience should be enhanced")



